run_modules:
  - custom_content

custom_content:
  order:
    - trimmomatic_report
    - fastqc_report
    - coverage_report
    - mash_RvSp_report
    - spades_report
    - mash_FAvNCBI_report
    - bwa_report
    - quast_report
    - nnn_gaps_report
    - qualimap_report
    - vcf_report

extra_fn_clean_exts:
  - type: regex_keep
    pattern: "^[^.]*"

export_plots: true
